version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
    expose:
      - "3306"
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
  backend:
    build: ./backend
    container_name: user-backend
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges: true
    read_only: true
    restart: always
    depends_on: 
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/userdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ./backend/logs:/app/logs
  frontend:
    build: ./frontend
    container_name: user-frontend
    restart: always
    ports:
      - "3000:80"
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    networks:
      - app-network
    volumes:
      - ./frontend/nginx:/etc/nginx/conf.d:ro

volumes:
  mysql_data:
networks:
  app-network:
    driver: bridge